### ISSUE TITLE
Frontend deployment patlayabilir - ENV Vars

### ISSUE THREAD

**Issue by gokhanozdemir** [onurdzd/DepremDanisma#175]
Patlarsa frontend deploy servisine env var eklenmeli
VITE_API_URL=https://depremdanismabackend.onrender.com/api

projenin github ayarlarında da env vars eklenebiliyor. Oradan da okuyor olabilir. 

@onurdzd

**Comment by onurdzd** [comment]
api adress .env içine alındı ve .env dosyaları gitignore eklendi.
